TransactionAnalysis/urls.py
"""
    TransactionAnalysis URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path as url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"", include(("accountmgmt.urls", "accountmgmt"), namespace="accountmgmt")),
    url(r"^", include(("txnanalytics.urls", "txnanalytics"), namespace="txnanalytics")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accountmgmt/urls.py
"""
    Used to manage all the URL's related to User Account
"""

from django.urls import path
# from accountmgmt.views import HomeView, RegistrationView, LoginView, LogoutView
from accountmgmt.views import RegistrationView, LoginView, LogoutView

urlpatterns = [
    # path('/', HomeView.as_view(), name="home"),
    path('register/', RegistrationView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # path('emailVerification/<uidb64>/<token>', activate, name='activate')
]

txnanalytics/urls.py
"""
    - Transaction Analytics URLs
"""

from django.urls import path

from txnanalytics.txn_history_view import TransactionHistoryView
from txnanalytics.views import (
    TransactionHistoryListView,
    UploadCsvView,
    PieChartFilterByTypeView
)

# app_name = "txnanalytics"


urlpatterns = [
    path("", TransactionHistoryListView.as_view(), name="txn_dashboard"),

    path('upload/csv/', UploadCsvView.as_view(), name='upload_csv'),
    path('ajax_datatable/transaction-history/list/',
        TransactionHistoryView, name="ajax_datatable_permissions"),

    path("filter-by/txn-category/",
        PieChartFilterByTypeView.as_view(), name="filter_by_txn_category"),
]

templates/common/page-content.html
{% load static %}

{% if pieChartData %}

    <style type="text/css">

        .pie-chart-filter { float: right; position: absolute; left: 63%; padding: 0px 0px 30px 0px; }

        .pie-chart-filter ul li{color: #AAAAAA; display: block; position: relative; float: left; width: 100%; height: 50px; }
        .pie-chart-filter ul li input[type=radio]{ position: absolute; visibility: hidden; }
        .pie-chart-filter ul li label{ display: block; position: relative; font-weight: 300; font-size: 24px; padding: 19px 0px 0px 57px; margin: 7px auto; height: 30px; z-index: 9; cursor: pointer; -webkit-transition: all 0.25s linear; }

        .pie-chart-filter ul li:hover label{ color: #007bff; font-weight: bold; }

        .pie-chart-filter ul li .check{ display: block; position: absolute; border: 3px solid #AAAAAA; border-radius: 100%; height: 24px; width: 25px; top: 30px; left: 20px; z-index: 5; transition: border .25s linear; -webkit-transition: border .25s linear; }

        .pie-chart-filter ul li:hover .check { border: 5px solid #FFFFFF; }

        .pie-chart-filter ul li .check::before { display: block; position: absolute; content: ''; border-radius: 100%; height: 10px; width: 9px; top: 2px; left: 3px; margin: auto; transition: background 0.25s linear; -webkit-transition: background 0.25s linear; }

        input[type=radio]:checked ~ .check { border: 5px solid #007bff; }

        input[type=radio]:checked ~ .check::before{ background: #007bff; }

        input[type=radio]:checked ~ label{ color: #007bff; }
    </style>


    <div style="float: left;">
        <div id="chartContainer" style="height: 300px; width: 100%;"></div>
    </div>


    <div class="pie-chart-filter">
        <ul>
            <li>
                <input type="radio" id="f-option" name="txnType" value="alltxn" checked data-url="{% url 'txnanalytics:filter_by_txn_category' %}" class="fetch-txn-pie-chart">
                <label for="f-option">All Transactions</label>
                <div class="check"></div>
            </li>
            <li>
                <input type="radio" id="s-option" name="txnType" value="credit" data-url="{% url 'txnanalytics:filter_by_txn_category' %}" class="fetch-txn-pie-chart">
                <label for="s-option">Credit</label>
                <div class="check"><div class="inside"></div></div>
            </li>
            <li>
                <input type="radio" id="t-option" name="txnType" value="debit" data-url="{% url 'txnanalytics:filter_by_txn_category' %}" class="fetch-txn-pie-chart">
                <label for="t-option">Debit</label>
                <div class="check"><div class="inside"></div></div>
            </li>
        </ul>
    </div>

    <script type="text/javascript">

        function loadPieChart(pieCharRawData, isAJAX, filterTxnType) {
            var pieDataPoints = [];

            for(var piedt=0; piedt<pieCharRawData.length; piedt++){
                var curr_data = pieCharRawData[piedt];
                var pieSliceData = {
                    y: curr_data.total,
                    label: curr_data.title.split("__").join(" "),
                    credit: "Credit: " + curr_data.credit,
                    debit: "Debit: " + curr_data.debit
                };

                if (isAJAX && filterTxnType == "credit")
                    delete pieSliceData["debit"]
                else if (isAJAX && filterTxnType == "debit")
                    delete pieSliceData["credit"]

                pieDataPoints.push(pieSliceData);
            }

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "Transaction Analysis[Month / Category(Credit-Debit) Wise]"
                },
                data: [{
                    type: "pie",
                    startAngle: 270,
                    // yValueFormatString: "Credit: 200, Debit: 300",
                    indexLabel: "{label} {credit} {debit}",
                    dataPoints: pieDataPoints
                }]
            });

            chart.render();
        }

        window.onload = function() {
            var pieCharRawData = {{pieChartData|safe}};
            var isAJAX = false;
            loadPieChart(pieCharRawData, isAJAX);        
        }


        $(".fetch-txn-pie-chart").on("change", function(event){
            var AJAX_URL = $(this).attr("data-url");
            
            $.ajax({
                url: AJAX_URL,
                data: {"txn_type": this.value},
                cache: false,
                type: "GET",
                success: function(response) {
                    var pieCharRawData = response.pieChartData;
                    var isAJAX = true;
                    loadPieChart(pieCharRawData, isAJAX, response.filterTxnType);
                },
                error: function(xhr) {
                    window.alert("Something went wrong!!! Please reload the page and try again.");
                }
            });
        })
    </script>

{% else %}
    Analytics Preview not available
{% endif %}

templates/common/sidebar.html
<div class="sidebar">
    <a class="{% if not 'upload' in request.path %} active {% endif %}" href="{% url 'txnanalytics:txn_dashboard' %}">
        Home
    </a>
    <a class="{% if 'upload' in request.path %} active {% endif %}" href="{% url 'txnanalytics:upload_csv' %}">
        Upload CSV
    </a>
</div>