TransactionAnalysis/urls.py
"""
    TransactionAnalysis URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path as url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"", include(("accountmgmt.urls", "accountmgmt"), namespace="accountmgmt")),
    url(r"^", include(("txnanalytics.urls", "txnanalytics"), namespace="txnanalytics")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accountmgmt/urls.py
"""
    Used to manage all the URL's related to User Account
"""

from django.urls import path
# from accountmgmt.views import HomeView, RegistrationView, LoginView, LogoutView
from accountmgmt.views import RegistrationView, LoginView, LogoutView

urlpatterns = [
    # path('/', HomeView.as_view(), name="home"),
    path('register/', RegistrationView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # path('emailVerification/<uidb64>/<token>', activate, name='activate')
]

txnanalytics/urls.py
"""
    - Transaction Analytics URLs
"""

from django.urls import path

from txnanalytics.txn_history_view import TransactionHistoryView
from txnanalytics.views import (
    TransactionHistoryListView,
    UploadCsvView,
    PieChartFilterByTypeView
)

# app_name = "txnanalytics"


urlpatterns = [
    path("", TransactionHistoryListView.as_view(), name="txn_dashboard"),

    path('upload/csv/', UploadCsvView.as_view(), name='upload_csv'),
    path('ajax_datatable/transaction-history/list/',
        TransactionHistoryView, name="ajax_datatable_permissions"),

    path("filter-by/txn-category/",
        PieChartFilterByTypeView.as_view(), name="filter_by_txn_category"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">


        {% block jsextra %}
            <script src="https://code.jquery.com/jquery-3.5.1.js"  crossorigin="anonymous"></script>
        {% endblock %}

        <title>Transaction Analysis Management</title>
    </head>
    <body>
        <style type="text/css">
            .alert-dismissible, .alert-success{
                margin-left: 18%;
            }
        </style>
        <header>
            {% include "header.html" %}
        </header>
        
        <div class="container" style="position: absolute; margin-top: 5%;">
            {% block content %}
                <!--Messages-->
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-dismissible alert-{{message.tags}}">
                      <button type="button" class="close" data-dismiss="alert">× </button>
                      <strong>{{message}}</strong>
                    </div>
                 {% endfor %}
                {% endif %}
                <!--End message-->
            {% endblock %}
        </div>

        <footer>
            {% block footer %}
                <!-- Optional JavaScript -->
                <!-- jQuery first, then Popper.js, then Bootstrap JS -->
                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            {% endblock %}
        </footer>

    </body>
</html>

templates/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block pagetitle %}
    <title>Dashboard</title>
{% endblock %}


{% block content %}
{% endblock %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if not request.user.is_authenticated %}
        <div>
            <a class="" href="{% url 'txnanalytics:txn_dashboard' %}">
                Home
            </a>
        </div>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
            <div class="nav-item dropdown" style="float: right;">
                <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item disabled" href="#">
                        {{request.user}}
                    </a>
                    <a class="dropdown-item" href="{% url 'accountmgmt:logout' %}">
                        Logout
                    </a>
                </div>
            </div>
        {% else %}
            <li class="nav-item">
                <a class="" href="{% url 'accountmgmt:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="" href="{% url 'accountmgmt:signup' %}">Signup</a>
            </li>
        {% endif %}
    </ul>
  </div>
</nav>

templates/home.html
{% include 'base.html' %}

<style type="text/css">
    body {
        overflow-x: hidden;
    }    
</style>

{% block content %}
    <div class="row">
        <div class="col-md-2">
            {% include "common/sidebar.html" %}
        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-12" style="max-width: 95%;left: 3%;">
                    <h2 style="margin-top: 7%; text-align: center;">
                        <u>
                            Transaction History
                        </u>
                    </h2>
                    {% include "transaction/transaction_history_list_view.html" %}
                    <script>
                        $(document).ready( function () {
                            $('#table_id').dataTable();
                        } );
                    </script>
                </div>
            </div>
            <div class="row" style="margin-top: 40px; border-top: 3px solid black; width: 98%; margin-left: 2%; margin-bottom: 12%;">
                <div class="col-md-12" style="margin-top: 40px;">
                    <div id="container" style="width: 75%;" class="load-pie-chart">
                        {% include "common/page-content.html" %}
                    </div> 
                </div>
            </div>
        </div>
    </div>

    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{% endblock %}