TransactionAnalysis/urls.py
"""
    TransactionAnalysis URL Configuration
"""
from django.contrib import admin
from django.urls import path, include, re_path as url

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"", include(("accountmgmt.urls", "accountmgmt"), namespace="accountmgmt")),
    url(r"^", include(("txnanalytics.urls", "txnanalytics"), namespace="txnanalytics")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accountmgmt/urls.py
"""
    Used to manage all the URL's related to User Account
"""

from django.urls import path
# from accountmgmt.views import HomeView, RegistrationView, LoginView, LogoutView
from accountmgmt.views import RegistrationView, LoginView, LogoutView

urlpatterns = [
    # path('/', HomeView.as_view(), name="home"),
    path('register/', RegistrationView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # path('emailVerification/<uidb64>/<token>', activate, name='activate')
]

txnanalytics/urls.py
"""
    - Transaction Analytics URLs
"""

from django.urls import path

from txnanalytics.txn_history_view import TransactionHistoryView
from txnanalytics.views import (
    TransactionHistoryListView,
    UploadCsvView,
    PieChartFilterByTypeView
)

# app_name = "txnanalytics"


urlpatterns = [
    path("", TransactionHistoryListView.as_view(), name="txn_dashboard"),

    path('upload/csv/', UploadCsvView.as_view(), name='upload_csv'),
    path('ajax_datatable/transaction-history/list/',
        TransactionHistoryView, name="ajax_datatable_permissions"),

    path("filter-by/txn-category/",
        PieChartFilterByTypeView.as_view(), name="filter_by_txn_category"),
]

templates/transaction/oldupload_csv_view.html
{% load static %}
{% include 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include "common/sidebar.html" %}
    </div>
    <div class="col-md-9">
        <div class="row" style="margin-top:200px">
            <div class="col-md-12 ">
                <div class="container">
<!--                    <div id="drop-area"  ondrop="drop(event)" ondragover="allowDrop(event)">-->
<!--                      <form class="my-form">-->
<!--                        <p>Upload multiple files with the file dialog or by dragging and dropping images onto the dashed region</p>-->
<!--                        <input type="file" id="fileElem" multiple accept="image/*" onchange="handleFiles(this.files)">-->
<!--                        <label class="button" for="fileElem">Select some files</label>-->
<!--                      </form>-->
<!--                    </div>-->

                    <form action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div class="file-upload-wrapper">
                            <input style="border:1px solid black;" type="file" id="input-file-now-custom-2" name="files" class="file-upload"
                                   data-height="500" multiple/>
                        </div>
                        <div class="show-files">
                            <ul>
                            </ul>
                        </div>
                        {% if errors %}
                        {% for key, value in errors.items %}
                        {{ key }} <br>
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Line No</th>
                                <th scope="col">Errors</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in value %}
                            <tr>
                                {% for line, error in i.items %}
                                <td>{{line}}</td>
                                <td>{{error}}</td>
                                {% endfor %}
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                        {% endfor %}
                        {% endif %}
                        <div class="row spacer">
                            <div class="">
                                <button type="submit" class="btn btn-sm btn-block btn-primary">Upload</button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>
$("input").on("input", function() {
  $(".show-files").show();
  var names = $(this).prop('files');
  for( var i = 0; i < names.length ; i++){
    console.log( names[ i ].name )
    $("ul").append("<li>" + names[ i ].name  + "</li>");
  }

});

</script>

templates/transaction/transaction_history_list_view.html
{% load static %}

<div class="table-responsive">
    <table id="datatable_permissions" width="100%" class="table table-striped table-bordered dt-responsive compact nowrap">
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="{% static 'lib/ajaxDatatable/js/utils.js' %}"></script>
<script src="//cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<link rel="stylesheet" type="text/css" href="{% static 'lib/ajaxDatatable/css/style.css' %}">

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css">

<script type="text/javascript" src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"></script>

<script language="javascript">
    $(document).ready(function() {
        AjaxDatatableViewUtils.initialize_table(
            $('#datatable_permissions'),
            "{% url 'txnanalytics:ajax_datatable_permissions' %}",
            {
                // extra_options (example)
                processing: false,
                autoWidth: false,
                full_row_select: true,
                scrollX: false
            }
        );
    });
</script>


<style type="text/css">
    #datatable_permissions_length {
        float: left;
    }
</style>

templates/transaction/upload_csv_view.html
{% load static %}
{% include 'base.html' %}

{% block content %}
<style>

    .files input {
    outline: 2px dashed #92b0b3;
    outline-offset: -10px;
    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
    transition: outline-offset .15s ease-in-out, background-color .15s linear;
    padding: 120px 0px 85px 35%;
    text-align: center !important;
    margin: 0;
    width: 100% !important;
}
.files input:focus{     outline: 2px dashed #92b0b3;  outline-offset: -10px;
    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
    transition: outline-offset .15s ease-in-out, background-color .15s linear; border:1px solid #92b0b3;
 }
.files{ position:relative}
.files:after {  pointer-events: none;
    position: absolute;
    top: 60px;
    left: 0;
    width: 50px;
    right: 0;
    height: 56px;
    content: "";
    background-image: url(https://image.flaticon.com/icons/png/128/109/109612.png);
    display: block;
    margin: 0 auto;
    background-size: 100%;
    background-repeat: no-repeat;
}
.color input{ background-color:#f1f1f1;}
.files:before {
    position: absolute;
    bottom: 10px;
    left: 0;  pointer-events: none;
    width: 100%;
    right: 0;
    height: 57px;
    content: " or drag it here. ";
    display: block;
    margin: 0 auto;
    color: #2ea591;
    font-weight: 600;
    text-transform: capitalize;
    text-align: center;
}
</style>
<div class="row">
    <div class="col-md-3">
        {% include "common/sidebar.html" %}
    </div>
    <div class="col-md-9">
        <div class="row" style="margin-top:200px">
            <div class="col-md-12 ">
                <div class="container">

                    <div class="container">
                            <div class="row">
                              <div class="col-md-6">
                                  <form action="" method="post" enctype="multipart/form-data" >
                                      {% csrf_token %}
                                      <div class="form-group files">
                                        <label>Upload Your File </label>
                                        <input type="file" name="files" class="form-control" multiple="">
                                      </div>
                                      <div class="row spacer">
                                        <div class="">
                                            <button type="submit" class="btn btn-sm btn-block btn-primary">Upload</button>
                                        </div>
                                    </div>
                                  </form>
                                  <div class="show-files">
                                    <ul>
                                    </ul>
                                </div>
                              </div>
                            </div>
                        </div>
                        {% if errors %}
                        {% for key, value in errors.items %}
                        <b>#{{ key }}</b> <br>
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Line No</th>
                                <th scope="col">Errors</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in value %}
                            <tr>
                                {% for line, error in i.items %}
                                <td>{{line}}</td>
                                <td>{{error}}</td>
                                {% endfor %}
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        {% endfor %}
                        {% endif %}
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>
$("input").on("input", function() {
  $(".show-files").show();
  var names = $(this).prop('files');
  for( var i = 0; i < names.length ; i++){
    console.log( names[ i ].name )
    $("ul").append("<li>" + names[ i ].name  + "</li>");
  }

});

</script>